### ISSUE TITLE
Specular component is exported wrong for pure metallic objects

### ISSUE THREAD

**Issue by TZZZZ** [mitsuba-renderer/mitsuba-blender#28]
Hi! Could you please help with the following? 

I have a simple scene in Blender with one camera, one cube, and one rectangular emitter (see attached). The cube has metallicity = 1 and specular = 0, i.e., it is pure metallic. We see a perfect reflection of the light source in Blender: 

<img width="376" alt="Screenshot 2022-08-24 at 17 48 03" src="https://user-images.githubusercontent.com/20816212/186477850-c7b06da8-b4c9-4558-80b9-b6956037a562.png">

However, after exporting the scene to xml using this add-on and rendering the obtained xml in Mitsuba3 I obtain a black screen. 

I think that the reason is as follows. The specular value in xml is exported as zero. It seems for me that in Mitsuba3 the specular parameter has another meaning and it should be exported as 0.5 in this case. If I change it manually to 0.5, I obtain the correct images in Mitsuba. 

[addon_test_metal.blend.zip](https://github.com/mitsuba-renderer/mitsuba-blender/files/9418056/addon_test_metal.blend.zip)

**Comment by TZZZZ** [comment]
Hi! Just in case I would like to ask for confirmation that I clearly explained that happens in this example and that you don't need other information.

**Comment by ros-dorian** [comment]
Hello,

After a bit of investigation, it seems that the `specular` parameter is simply another way of expressing the `eta` value in a way that is more easily understandable by artists. Both Mitsuba and Blender convert the `specular` value into an `eta` IOR using the formula $\text{specular} = \frac{1}{0.08}(\frac{\text{eta}-1}{\text{eta}+1})^2$. You can find this information in [Blender's manual](https://docs.blender.org/manual/en/latest/render/shader_nodes/shader/principled.html#inputs) and in [Mitsuba's code](https://github.com/mitsuba-renderer/mitsuba3/blob/86647607c2548dcc65927bb12be56a235e475cf5/src/bsdfs/principled.cpp#L229).

The primary difference between Blender and Mitsuba is that Blender, on one hand, has both an IOR **and** a specular value. In this case, the IOR value affects the transmittance only whereas the specular value handles the fresnel coefficient for dielectric and metallic materials. On the other hand, Mitsuba only has **one** value for both effects which can either be defined as `eta` directly or using the converted `specular` value.

All of that to say that, in my opinion, the bug is not about the specular value itself but rather an incorrect behavior in Mitsuba with $\text{specular} = 0$ (or $\text{eta} = 1$).

A simple fix for now can be to avoid the problematic values by adding some epsilon, which seems to produce correct images. However, it would be interesting on top of that to export either Blender's IOR or specular value depending on whether the material has a transmission component.

Let me know if all of this makes sense or if I am missing something. I will let this issue open until we have some more opinion from people that know Mitsuba in details :) @dvicini

**Comment by ros-dorian** [comment]
One more thing to note is that any `transmission` value that is not completely 0 or 1 will lead to inconsistent results between Mitsuba and Blender unless the `specular` and `eta` values are matched in Blender. You can find a very interesting video [here](https://www.youtube.com/watch?v=s0VlyRbj-yQ) that explains how to do this in the shader editor (and achieve better realism).

Basically, it comes down to two different implementation philosophies. Blender wants to give artists control over the appearance of the material and Mitsuba aims at physical realism.

**Comment by TZZZZ** [comment]
Yes, thank you, it works with specular=epsilon.

**Comment by ros-dorian** [comment]
Great, I've merged the temporary fix but I'll leave this issue open until further investigation.

**Comment by ros-dorian** [comment]
Closing this issue as it is mostly solved.
