### ISSUE TITLE
Failed to load Mitsuba package.

### ISSUE THREAD

**Issue by mengyuan-lee** [mitsuba-renderer/mitsuba-blender#83]
**Issue Title**
Failed to load Mitsuba package.

**Bug Description**
When I install this package in Blender 3.3 as suggested, it always returns "Failed to load Mitsuba package.". I checked the source code and found that it is aroused by exception in init_mitsuba(context). But I do not find out how to fix it.

I have tried different versions of python and different versions of Blender, neither works.

**Comment by bathal1** [comment]
Could you please provide more details regarding your setup ? What OS are you using, how did you install the add-on, which version ? Did you click on "install dependencies via pip" in the addon settings ? Or are you trying to use a custom Mitsuba build ?

**Comment by mengyuan-lee** [comment]
I use it on win10. I added it (I tried both v2 and v3) into blender 3.3 by clicking “edit”, “preferences”,  “add-ons”, “install”, and selecting the zip archive. There is no button about “install dependencies via pip”, just a button about “update dependencies”. I clicked it and found that “failed to load mitsuba”. I have tried to use a custom mitsuba build. I used “pip install mitsuba” in cmd and mitsuba 5.0 was installed. I copied the path of mitsuba 5.0 to install the addon in blender, but it returned “failed to load custom mitsuba. Please verify the path to the build directory.”.在 2023年12月23日，01:28，Baptiste Nicolet ***@***.***> 写道：﻿
Could you please provide more details regarding your setup ? What OS are you using, how did you install the add-on, which version ? Did you click on "install dependencies via pip" in the addon settings ? Or are you trying to use a custom Mitsuba build ?

**Comment by bathal1** [comment]
When using versions of blender before 3.5, you will need to run blender with the flag `--python-use-system-env` in order for it to find the packages installed via pip when clicking on "Install/update dependencies". Please try the following:

- Open a command line prompt. (press Windows + R, write cmd, press enter)
- In the terminal, paste: `"C:\Program Files\Blender Foundation\Blender 3.3\blender.exe" --python-use-system-env` (It's possible that the path to the blender executable is different on your system, you might have to adjust that.) and press enter. 

Blender should now be able to load mitsuba, please let me know if it doesn't

Please also note that the "custom build" you are describing is not what we mean by that. Installing mitsuba via pip in a different python environment will likely lead to errors because of mismatches between versions of mitsuba and/or python. The intended way is to clone mitsuba and build it, and then put the path to the build folder in the addon settings. This is usually not necessary though, as installing the packages via pip should work in most cases.

**Comment by mengyuan-lee** [comment]
It works now. Thanks.

**Comment by zhou-wb** [comment]
I am using Blender 4.2 on Win10 but I also need to run blender with the flag --python-use-system-env. Otherwise it always returns "Failed to load Mitsuba package."
