### ISSUE TITLE
Importer: "enum 'SHARP' not found" with Torus

### ISSUE THREAD

**Issue by pablode** [mitsuba-renderer/mitsuba-blender#99]
**Bug Description**
Mitsuba-blender fails to import the Torus asset from https://www.mitsuba-renderer.org/download.html.

**To Reproduce**
1. Import Torus asset XML
2. See error being thrown

**Expected behavior**
No error.

**Resources**
<img width="918" alt="Screenshot 2024-05-01 at 22 51 08" src="https://github.com/mitsuba-renderer/mitsuba-blender/assets/3663466/314f321c-41fa-45d5-9ed5-2af92f75f6b5">

**Environment:**
 - OS: MacOS Sonoma 14.4.1
 - Blender Version: 4.0.2
 - Add-on Version: v0.4.0

**Comment by bathal1** [comment]
Hi, 
Thanks for bringing this up, a fix will be incorporated soon. 

Please note that importing this particular scene will still not work, because this is a Mitsuba **0.6** scene, which contains plugins that are no longer supported by Mitsuba 3. In particular, the integrator and the Sun-Sky model are not supported anymore. Furthermore, the importer is currently unable to import geometry from the `serialized` file format. 

In order to work around these issues, I suggest you remove/replace the unsupported plugins, load the geometry using Mitsuba's python API, and export the meshes one by one as PLYs.

**Comment by pablode** [comment]
Thanks for the detailed answer!
